### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by schnabel45** [Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate#1]
It appears there are issues with ResponseContent.cs which prevent compiling using DotNet Core 3.1.301. Namely it looks like string and character literals are being mixed up, also the status string was not included in the class definition. Opening this issue so I can submit a pull request with a fix.

**Comment by rajmsft** [comment]
I still get the compile error. I have core 3.1.301 installed. Same error message - character / string mixed up

**Comment by schnabel45** [comment]
Pull request #2 was merged in, so this can now be closed.
