### ISSUE TITLE
Images broken in ReadMe

### ISSUE THREAD

**Issue by katiep23** [Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate#12]
Broken links: https://github.com/Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate/raw/master/images/api-connector-configuration.png

https://github.com/Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate/raw/master/images/api-connector-selected.png

**Comment by nickgmicrosoft** [comment]
Resolved
