### ISSUE TITLE
Content Response ShowBlockPage is only working when version is set to "0.0.1"

### ISSUE THREAD

**Issue by aripp** [Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate#6]
I've registered an API connector during sign up user flow (before user creation). In some situations I like to abort the sign up process with an error message. Therefore my API does return a response content object created with the class below.  I wonder why the Azure B2C Directory does ignore my content response when I set the version string to "1.0.0" instead of "0.0.1" According to the documentation the version string "1.0.0" should work as well. [https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector#example-of-a-blocking-response](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector#example-of-a-blocking-response)
However the documentation is not very clear. It states "The version of the API.". My API or the B2C Directory API Version?

`
    public class ShowBlockPageResponseContent
    {
        public const string ApiVersion = "0.0.1";

        public ShowBlockPageResponseContent(string userMessage)
        {
            //this.version = ShowBlockPageResponseContent.ApiVersion;
            this.action = "ShowBlockPage";
            this.userMessage = userMessage;
            this.status = "400";
        }

        public string version { get; }
        public string action { get; set; }
        public string userMessage { get; set; }
        public string status { get; set; }
    }`

Help is welcome :-)

**Comment by yoelhor** [comment]
The `ShowBlockPage` works with any version you specify. The version has no impact of the user flow. 

There were some issues related to the `ShowBlockPage` event. For more information, see the [#9 pool request description](https://github.com/Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate/pull/9). 
 Please see the [PR](https://github.com/Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate/pull/9/files) changes.
