### ISSUE TITLE
Continue content response with updated claim is ignored by Azure B2C Directory 

### ISSUE THREAD

**Issue by aripp** [Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate#7]
I've registered an API connector during sign up user flow (before user creation). In some situations I like to update some claim that the user entered during sign up. Therefore my API does return a response content object created with the class below. 
The problem is that the Azure B2C does ignore my continue response object. The created user object contains the streetAddress value that the user entered in the sign up form. My API receives that data when get called form B2C but I'm not able to override the value with "XXXXX" with my continue response object.

`
    public class ContinueResponseContent
    {
        public const string ApiVersion = "0.0.1";

        public ContinueResponseContent()
        {
            this.version = ContinueResponseContent.ApiVersion;
            this.action = "Continue";
            this.streetAddress = "XXXXXXX"; //Test overriding the steetAddress claim the user provided during sign up 
        }

        public string version { get; }
        public string action { get; set; }
        public string status { get; set; }
        public string streetAddress { get; set; }
    }
`
Help is welcome :-)

**Comment by yoelhor** [comment]
Closing this issue due to the [pull request 10](https://github.com/Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate/pull/10) fix. In the new example, the API Connector returns a static value for the job title.
